spring:
  application:
    name: siserkom-api
  datasource:
    url: jdbc:mariadb://localhost:3307/siserkom
    username: root
    password: password
#  jpa:
#    show-sql: true
server:
  port : 8088
  servlet:
    context-path: /siserkom/v4
  forward-headers-strategy: framework

#logging:
#  file:
#    path: /tmp
#  level:
#    id.ac.arraniry.siserkomapi: trace

env:
  data:
    app-key: ""
    secret-key: ""
    cdn-password: ""
