spring:
  application:
    name: siserkom-api
  datasource:
    url: jdbc:mariadb://localhost:3307/siserkom
    username: root
    password: password
server:
  port : 8088
  servlet:
    context-path: /siserkom/v4
  forward-headers-strategy: framework

logging:
  file:
    path: /tmp
  level:
    id.ac.arraniry.siserkomapi: trace
